FROM docker.m.daocloud.io/node:18-alpine AS builder

WORKDIR /app

# Install dependencies
COPY monitor/ui/package.json monitor/ui/package-lock.json ./
RUN npm install

# Copy source
COPY monitor/ui ./

# Build
# Ensure binaries are executable and NEXT_PUBLIC_API_URL is set
ENV NEXT_PUBLIC_API_URL=/api
RUN chmod -R +x node_modules/.bin && npm run build

# Runner stage
FROM docker.m.daocloud.io/node:18-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME=0.0.0.0

CMD ["node", "server.js"]
